server:
  port: 8080


bootext:
  cacheName: hoopoe


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hoopoe?serverTimezone=GMT%2B8
    username: root
    password: root
    db-name: hoopoe
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 2
      max-active: 10
      min-idle: 2
      pool-prepared-statements: true
      validation-query: select 1
      filters: stat, wall, config, slf4j
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
        slf4j:
          enabled: true
    #filters: wall,mergeStat
    jmx-enabled: false
    #driver-class-name: com.mysql.driver.JDBCDriver
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    min-idle: 5
  #    max-active: 50
  #    max-wait: 6000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
      #连接超时时间
      timeout: 10000

  cache:
    type: redis
    redis:
      time-to-live: 1
#flowable:
#  database-schema-update: true
#  process:
#    definition-cache-limit: 1
##  activityFontName: \u5B8B\u4F53
##  labelFontName: \u5B8B\u4F53
##  annotationFontName: \u5B8B\u4F53
#  xml:
#    encoding: UTF-8

#
#logging:
#  level:
#    root: warn
#    org:
#      spring: warn
#    com:
#      alibaba: warn
#    cn:
#      hutool: warn
#    hoopoe: warn
#  path: ./logs
management:
  endpoints:
    web:
      base-path: /api/v1/actuator