server:
  port: 8080


bootext:
  cacheName: hoopoe


spring:
  # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
 #p6spy: true
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/hoopoe?serverTimezone=GMT%2B8
      username: root
      password: root
      db-name: hoopoe
      initial-size: 2
      max-active: 10
      min-idle: 2
      pool-prepared-statements: true
      validation-query: select 1
      filters: stat, wall, config, slf4j
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
        slf4j:
          enabled: true
    #filters: wall,mergeStat
    jmx-enabled: false
    #driver-class-name: com.mysql.driver.JDBCDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    type: com.alibaba.druid.pool.DruidDataSource
#    min-idle: 5
#    max-active: 50
#    max-wait: 6000
  jmx: false

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
      #连接超时时间
      timeout: 10000

  cache:
    type: redis
    redis:
      time-to-live: 1


hoopoe:
  anon-url: /api/v1/login,/api/v1/logout


logging:
  level:
    root: debug
    org:
      spring: debug
    com:
      alibaba: debug
    cn:
      hutool: debug
    hoopoe: debug
  path: ./logs
management:
  endpoints:
    web:
      base-path: /api/v1/actuator
